apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  name: {{ .Values.deployment.app }}-loadbalancer
  namespace: {{ .Values.deployment.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.deployment.app }}